apiVersion: v1
kind: ConfigMap
metadata:
  name: fundandtrace-config
  namespace: fundandtrace
data:
  NODE_ENV: "production"
  PORT: "5000"
  MAINURL: "https://fundandtrace.com"
  BACKENDURL: "https://api.fundandtrace.com"
  NEXT_PUBLIC_API_URL: "https://api.fundandtrace.com"
