apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fundandtrace-ingress
  namespace: fundandtrace
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
    - hosts:
        - fundandtrace.com
        - www.fundandtrace.com
        - api.fundandtrace.com
      secretName: fundandtrace-tls
  rules:
    - host: fundandtrace.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fundandtrace-frontend-svc
                port:
                  number: 3000
    - host: www.fundandtrace.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fundandtrace-frontend-svc
                port:
                  number: 3000
    - host: api.fundandtrace.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fundandtrace-backend-svc
                port:
                  number: 5000
